// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRu3IMjdzvylBmmoL7P9jg9N_dXvKVJfc',
    appId: '1:856379312283:web:78f35f75e9296a1cb11e3e',
    messagingSenderId: '856379312283',
    projectId: 'flashcard-app-dd04d',
    authDomain: 'flashcard-app-dd04d.firebaseapp.com',
    storageBucket: 'flashcard-app-dd04d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZpdIgG9wy_OFGGQXG-3KPvm9yy2-DRE',
    appId: '1:856379312283:android:a0191db0f2f66dc4b11e3e',
    messagingSenderId: '856379312283',
    projectId: 'flashcard-app-dd04d',
    storageBucket: 'flashcard-app-dd04d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGaOcJneDCnF2ztkdx29A5s87U7xJnPq4',
    appId: '1:856379312283:ios:fe59c1f65d825de5b11e3e',
    messagingSenderId: '856379312283',
    projectId: 'flashcard-app-dd04d',
    storageBucket: 'flashcard-app-dd04d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGaOcJneDCnF2ztkdx29A5s87U7xJnPq4',
    appId: '1:856379312283:ios:fe59c1f65d825de5b11e3e',
    messagingSenderId: '856379312283',
    projectId: 'flashcard-app-dd04d',
    storageBucket: 'flashcard-app-dd04d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRu3IMjdzvylBmmoL7P9jg9N_dXvKVJfc',
    appId: '1:856379312283:web:802c03c79b54d39bb11e3e',
    messagingSenderId: '856379312283',
    projectId: 'flashcard-app-dd04d',
    authDomain: 'flashcard-app-dd04d.firebaseapp.com',
    storageBucket: 'flashcard-app-dd04d.firebasestorage.app',
  );
}
